### ISSUE TITLE
Does this patch work for HD4400?

### ISSUE THREAD

**Issue by slikie** [coderobe/AzulPatcher4600#1]
These two models are similar enough I guess it's no harm to ask

**Comment by coderobe** [comment]
I am not sure. I don't have a mobile HD4400 to test this on.

This patch likely also depends on a specific topology where the internal display is connected using lvds and you only have one external hdmi port - but if that's the case you could try it.

**Comment by slikie** [comment]
This patch doesn't seem to do any difference to my gear.
Thank you for your work and patience though.
Issue closed.

**Comment by coderobe** [comment]
When loaded, it should definitely do something noticeable - if it's not compatible it would most likely break  your graphics and/or multi monitor setups. Are you sure the kext got loaded properly?
