### ISSUE TITLE
Not work with HS

### ISSUE THREAD

**Issue by Slbomber** [coderobe/AzulPatcher4600#2]
This kext not work in Lilu 1.2 and High Sierra 10.13, please update source code and patches!

**Comment by coderobe** [comment]
I have been working on an update, i'll release it once it's stable enough.

**Comment by coderobe** [comment]
Fixed with https://github.com/coderobe/AzulPatcher4600/commit/6aba6b9d117f6e046674c582e8ffdf052e0ee14a
