### ISSUE TITLE
AzulPatcher4600.kext.zip

### ISSUE THREAD

**Issue by webfalter** [coderobe/AzulPatcher4600#4]
Wärst Du so lieb und würdest deine Release wie die anderen in der zip mit Versionsnummer benennen. So in der Art 1.2.0.RELEASE.zip oder AzulPatcher4600.1.2.0.kext.zip, das man sie nach den Download unterscheiden kann.

DANKE

**Comment by coderobe** [comment]
Rückwirkend werde ich an dem Namensschema nichts verändern. Die Versionsnummer steht in der Download-URL & alle Versionen sind abwärtskompatibel, ich sehe keinen grund mehrere Versionen zu behalten - außerdem kann das Archiv auch nach dem Download umbenannt werden ;)
