### ISSUE TITLE
[ASK] How to Re-Enable AppleIntelFramebuffer@2

### ISSUE THREAD

**Issue by kholisrag** [coderobe/AzulPatcher4600#5]
Bro... How to? Re-Enable AppleIntelFramebuffer@2, because I think my HDMI jack is connected to there... when I plug it in, In don't work...

**Comment by coderobe** [comment]
Sounds like your port topology is different. Can you post a dump of your pci devices? You can do that using DPCIManager for example.

**Comment by kholisrag** [comment]
Here... 
<img width="1021" alt="screenshot at dec 18 16-12-12" src="https://user-images.githubusercontent.com/4683704/34098250-4644222c-e40e-11e7-914e-4e64673235f9.png">
<img width="1029" alt="screenshot at dec 18 16-12-20" src="https://user-images.githubusercontent.com/4683704/34098251-467e5d48-e40e-11e7-8e99-dd52c232d3b0.png">

**Comment by coderobe** [comment]
I don't think you have to use my kext on your system.
What are the symptoms you get without the kext?

**Comment by kholisrag** [comment]
My HDMI is not working...
I tried this... but don't work...
<img width="985" alt="screenshot at dec 18 18-47-47" src="https://user-images.githubusercontent.com/4683704/34104696-21f884ba-e424-11e7-94ac-f21cf903b136.png">

**Comment by coderobe** [comment]
The patches you applied are for hdmi audio, not video.

On another note: AzulPatcher4600 will **not** fix any broken hdmi video either.
